ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: "nginx"  
  hosts:
    - host: rralab-obs.do.support.rancher.space
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: suse-observability-ui
              port: 
                number: 443
  tls:
    - hosts:
      - rralab-obs.do.support.rancher.space
      secretName: observability-tls-secret